### ISSUE TITLE
`bindparam` leads to erronously repeated clause elements

### ISSUE THREAD

**Issue by linozen** [havok2063/boolean_parser#11]
The `bindparam` function used to bind values when comparing strings with `=` or `==` leads to the following erroneous SQL queries being emitted to the database.

For example, the following clause
```plaintext
supporter_amount=10 and (zip=53* or zip=54*)
```

leads to the following SQL query (only `WHERE` clause is included):
```sql
...
WHERE person.supporter_amount = 10.0 
  AND (lower(person.zip) ILIKE '54%' 
  OR lower(person.zip) ILIKE '54%')
```

As you can see, the last element of the `OR` clause overwrites the first. This bug is fixed when removing the `bindparam` function in [this code here](https://github.com/havok2063/boolean_parser/blob/main/boolean_parser/mixins/sqla.py#L202-L204).

**Comment by havok2063** [comment]
Finally merging and closing this.  Sorry for the long delay.
