### ISSUE TITLE
from database.models import TableModel error

### ISSUE THREAD

**Issue by anisengupta** [havok2063/boolean_parser#2]
Hi, I am trying to use the boolean-parser module but I am having trouble with importing the relevant modules:

![image](https://user-images.githubusercontent.com/62817385/107529259-98fcff00-6bb2-11eb-8b65-f8fcfe1b0699.png)

Do you know what this error might be?

Thanks,
Aniruddha

**Comment by havok2063** [comment]
@anisengupta Are you trying to copy and paste the examples from the documentation?  Those are just toy examples and don't represent real code.  Essentially wherever you see `from database import session` you should replace with your import of an instantiated SQLAlchemy database Session, and wherever you see `from database.models import TableModel` you should replace with your imports of your defined SQLAlchemy Models you want to use in the parser.

But you make a good point that perhaps I should update the documentation to clarify that it's a toy example, meant to be replaced by real code.  I'll create a separate issue for that.
