### ISSUE TITLE
SQLParser doesn't understand relationship field names.

### ISSUE THREAD

**Issue by jamwil** [havok2063/boolean_parser#7]
Thank-you for your work on this package. I'm curious if its possible to have the parser understand relationship field names like the sister project `marvin-sqlalchemy-boolean-search` appears to?

I would use that, however it doesn't allow SQLAlchemy >= 1.4.

**Comment by havok2063** [comment]
Hmm, I thought I ported over all of the functionality in that project into this one.  But maybe not.  Can you clarify what you mean by "relationship field names" and provide an example of how it used to work in `marvin-sqlalchemy-boolean-search`?  I'm hoping to fully deprecate that package in favor of this one.

**Comment by jamwil** [comment]
Let's say, for instance, that you have the following ORM base models (bottom of this post). I want to parse an expression against the `Person` object, it works as expected with a query like `people.first_name == James` or even just `first_name == James`.

Where I run into trouble is something like `location.locality == Calgary`. I get an error that says `Table people does not have field locality`. Likewise, if I try to fully qualify it and go `people.location.locality == Calgary`, I get `parameter people.location.locality cannot have more than one .`

I haven't tried it as I'm using SQLAlchemy 1.4, but the documentation for the other project states that I can do something like `"field1=*something* and not (field2==1 or parent.field3<=10.0)"`, which I think is the functionality that I'm after (note the parent.field3 part). Moreover, the README for that project says *Relationship field names such as 'parent.grandparent.name' are accepted.* This no longer appears to be the case with this implementation.

Happy to submit a PR if you can point me in the right direction on how to do this. I'm pretty new to pyparsing. TIA.

```python
class Person(Base):
    """Defines the SQLAlchemy ORM for the People table."""

    __tablename__ = "people"

    id = Column(Integer, primary_key=True)
    location_id = Column(Integer, ForeignKey("DS.locations.id"))
    first_name = Column(String, nullable=False)
    middle_name = Column(String)
    last_name = Column(String, nullable=False)
    credentials = Column(String)
    title = Column(String)
    phone = Column(String)
    email = Column(String)

    location: Location = relationship("Location", back_populates="people")
    companies: List[Company] = relationship(
        "Company", secondary=person_company_table, back_populates="people"
    )


class Location(Base):
    """Defines the SQLAlchemy ORM for a company's location."""

    __tablename__ = "locations"

    id = Column(Integer, primary_key=True)
    description = Column(String)
    address = Column(String)
    locality = Column(String)
    province = Column(String)
    postal_code = Column(String)
    phone = Column(String)
    fax = Column(String)

    people: List[Person] = relationship("Person", back_populates="location")
    companies: List[Company] = relationship(
        "Company", secondary=location_company_table, back_populates="locations"
    )
```

**Comment by havok2063** [comment]
Ahh ok, I see what you mean now.  That line in README of the `marvin-sqlalchemy-boolean-search` was there from the original fork.  I don't know if I explicitly checked that that the behavior was possible in `marvin-sqlalchemy-boolean-search`.  But I agree it'd be nice to have here.  I'll have to think on it and get back to.  If it's an easy enough change I'm happy to point you in the right direction for a PR.

**Comment by havok2063** [comment]
@jamwil I had a chance to look into this.  First, there was a small typo in your example.  The tablename for the `Location` ORM is `locations`, not `location`, so `location.locality == Calgary` should be `locations.locality == Calgary` which works correctly.  But `people.location.locality == Calgary` does not work.  

Currently, the code only supports a single `.` separator, in the input parameter name, i.e. `db_table_name.column_name`.  e.g. `people.first_name`.   So it doesn't support relationships in that way.  The code has to do two main things:  first, parse the string name into a db table, and column name, and then it has to check and look up that column name in the provided ORM when a `filter` command is issued, e.g. `f=p.filter([Person, Location])`.  With multiple `.` separators, there is no easy way to distinguish between schema and tables, i.e. `db_schema_name.db_table_name.column_name` and `db_table_name.joined_table_name.joined_column_name`.   We'd also have to improve the logic for identifying which ORM the column belongs to.  

You can still manually join the tables.  This should work
```
p = parse('people.first_name == Bob and locations.locality==Calgary')
f = p.filter([Person, Location])
session.query(Person).join(Location).filter(f).all()
```

The code for parsing the input parameter string into its proper table + column names is the [_parse_parameter_name](https://github.com/havok2063/boolean_parser/blob/aeb3376479f5e8a2c424e0ff3b5fe3d96e418fb9/boolean_parser/actions/clause.py#L53) method in the base Action class.  And for the code that performs the lookup between column and ORM , see the [filter](https://github.com/havok2063/boolean_parser/blob/aeb3376479f5e8a2c424e0ff3b5fe3d96e418fb9/boolean_parser/mixins/sqla.py#L103) and [_get_field](https://github.com/havok2063/boolean_parser/blob/aeb3376479f5e8a2c424e0ff3b5fe3d96e418fb9/boolean_parser/mixins/sqla.py#L69) methods in the SQL mixin parser class.  Feel free to take a look and submit a PR.   If I can find some time, I'll try to poke at it.

**Comment by jamwil** [comment]
My apologies for the delayed reply to this. Thank-you for taking a look! I'll play with it more this week.
